workflows:
  react-native-ios-internal:
    name: UAWauto iOS Build

    integrations:
      app_store_connect: UAW_API_Key

    environment:
      ios_signing:
        certificates:
          - UAW_Certificate              # 👈 Reference name from Codemagic UI
        provisioning_profiles:
          - UAW_Provision_Profile       # 👈 Reference name from Codemagic UI

      vars:
        XCODE_WORKSPACE: "ios/UAWauto.xcworkspace"
        XCODE_SCHEME: "UAWauto"
        BUNDLE_ID: "com.uawauto.uaw"

      node: 18.16.0
      xcode: latest

    scripts:
      - name: Install JS & CocoaPods dependencies
        script: |
          npm ci
          cd ios && pod install

      - name: Increment build number
        script: |
          cd ios
          agvtool new-version -all "$BUILD_NUMBER"

      - name: Apply signing assets
        script: |
          xcode-project use-profiles --project "ios/UAWauto.xcodeproj" --warn-only

      - name: Build & export .ipa
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

      - name: List produced artifacts
        script: |
          find build/ipa -type f

    artifacts:
      - build/ipa/*.ipa
      - $CM_BUILD_DIR/UAWauto.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - UAW-Auto Internal Testing
        submit_to_app_store: true
