workflows:
  ios-manual-sign:
    name: iOS Manual Code Signing Workflow

    environment:
      node: 18.16.0                 # 👈  use RN‑supported Node
      xcode: latest
      vars:
        APP_PROFILE_PATH: "ios/Uaw_Auto.mobileprovision"
        P12_CERT_PATH:    "ios/uaw_certificate.p12"
        CERTIFICATE_PASSWORD: LWXAxSMY
        EXPORT_OPTIONS_PLIST: "ios/exportOptions.plist"
        BUNDLE_ID: "com.uawauto.uaw"

    scripts:
      # 1️⃣  JS deps first — generates node_modules/react-native/…
      - name: Install JS dependencies
        script: |
          npm ci

      # 2️⃣  iOS pods next — now Podfile can resolve RN scripts
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      # 3️⃣  Certificate → keychain
      - name: Install certificate
        script: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import "$P12_CERT_PATH" -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

      # 4️⃣  Provisioning profile → Library/MobileDevice
      - name: Install provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(grep -ao '<UUID>.*</UUID>' "$APP_PROFILE_PATH" | sed -E 's:<(/)?UUID>::g')
          echo "Using profile UUID: $PROFILE_UUID"
          cp "$APP_PROFILE_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/"$PROFILE_UUID".mobileprovision

      # 5️⃣  Patch pbxproj for manual signing
      - name: Apply manual signing to Xcode project
        script: |
          xcode-project use-profiles

      # 6️⃣  Build archive (.xcarchive)
      - name: Build iOS archive
        script: |
          xcodebuild -workspace ios/UAWauto.xcworkspace \
            -scheme UAWauto \
            -archivePath "$CM_BUILD_DIR/UAWauto.xcarchive" \
            archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            OTHER_CODE_SIGN_FLAGS="--keychain build.keychain"

      # 7️⃣  Export signed .ipa
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/UAWauto.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "$CM_BUILD_DIR/build/ios"
