workflows:
  ios-manual-sign:
    name: iOS Manual Code Signing Workflow
    environment:
      vars:
        CERTIFICATE_PASSWORD: EncryptedPasswordHere  # optional; use encryption
        APP_PROFILE_PATH: "ios/certificates/profile.mobileprovision"
        P12_CERT_PATH: "ios/certificates/certificate.p12"
        EXPORT_OPTIONS_PLIST: "ios/exportOptions.plist"
        BUNDLE_ID: "com.your.bundle.id"
      xcode: latest
    scripts:
      - name: Install certificate
        script: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import $P12_CERT_PATH -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

      - name: Install provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(grep -a -o '<UUID>.*</UUID>' $APP_PROFILE_PATH | sed -e 's/<UUID>//' -e 's:</UUID>::')
          cp $APP_PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision

      - name: Set signing style
        script: |
          xcode-project use-profiles  # still needed to apply manual settings

      - name: Build iOS archive
        script: |
          xcodebuild -workspace ios/UAWauto.xcworkspace \
            -scheme UAWauto \
            -archivePath $CM_BUILD_DIR/UAWauto.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID"

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/UAWauto.xcarchive \
            -exportOptionsPlist $EXPORT_OPTIONS_PLIST \
            -exportPath $CM_BUILD_DIR/build/ios
