workflows:
  ios-manual-sign:
    name: iOS Manual Code Signing Workflow

    environment:
      node: 18.16.0
      xcode: latest
      vars:
        APP_PROFILE_PATH: "ios/Uaw_Auto.mobileprovision"
        P12_CERT_PATH: "ios/uaw_certificate.p12"
        CERTIFICATE_PASSWORD: LWXAxSMY
        EXPORT_OPTIONS_PLIST: "ios/exportOptions.plist"
        BUNDLE_ID: "com.uawauto.uaw"

    scripts:
      - name: Install JS dependencies
        script: |
          set -ex
          npm ci

      - name: Install CocoaPods dependencies
        script: |
          set -ex
          cd ios
          pod install --repo-update

      - name: Install certificate
        script: |
          set -ex
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import "$P12_CERT_PATH" -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

      - name: Install provisioning profile
        script: |
          set -ex
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
              
              # Decode and extract UUID from .mobileprovision
          PROFILE_UUID=$(security cms -D -i "$APP_PROFILE_PATH" | /usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin)
    
          if [ -z "$PROFILE_UUID" ]; then
            echo "❌ Failed to extract PROFILE_UUID from $APP_PROFILE_PATH"
            exit 1
          fi
    
           echo "✅ Using provisioning profile UUID: $PROFILE_UUID"
          cp "$APP_PROFILE_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/"$PROFILE_UUID".mobileprovision
    
              # Export it for later steps
          echo "export PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV

      - name: Apply manual signing to Xcode project
        script: |
          set -ex
          xcode-project use-profiles --project ios/UAWauto.xcodeproj

      - name: Build iOS archive
        script: |
          set -ex
          echo "🔒 Using PROFILE_UUID=$PROFILE_UUID"
          xcodebuild -workspace ios/UAWauto.xcworkspace \
            -scheme UAWauto \
            -archivePath "$CM_BUILD_DIR/UAWauto.xcarchive" \
            archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            OTHER_CODE_SIGN_FLAGS="--keychain build.keychain"

      - name: Export IPA
        script: |
          set -ex
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/UAWauto.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "$CM_BUILD_DIR/build/ios"
