workflows:
  ios-manual-sign:
    name: iOS Manual Code Signing Workflow

    environment:
      node: 18.16.0
      xcode: latest
      vars:
        APP_PROFILE_PATH: "ios/UAW_Provision_Profile.mobileprovision"
        P12_CERT_PATH: "ios/uaw_certificate.p12"
        CERTIFICATE_PASSWORD: LWXAxSMY
        EXPORT_OPTIONS_PLIST: "ios/exportOptions.plist"
        BUNDLE_ID: "com.uawauto.uaw"

    scripts:
      - name: Install JS dependencies
        script: |
          set -ex
          npm ci

      - name: Install CocoaPods dependencies
        script: |
          set -ex
          cd ios
          pod install --repo-update

      - name: Install certificate
        script: |
          set -ex
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import "$P12_CERT_PATH" -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

      - name: Install provisioning profile
        script: |
          set -ex
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID="f4743f55-d063-482c-817a-982fb1be0b31"
          echo "Using profile UUID: $PROFILE_UUID"
          cp "$APP_PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV

      - name: Apply manual signing to Xcode project
        script: |
          set -ex
          xcode-project use-profiles --project ios/UAWauto.xcodeproj

      - name: Build iOS archive
        script: |
          set -ex
          echo "🔒 Using PROFILE_UUID=$PROFILE_UUID"
          xcodebuild -workspace ios/UAWauto.xcworkspace \
            -scheme UAWauto \
            -archivePath "$CM_BUILD_DIR/UAWauto.xcarchive" \
            archive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            DEVELOPMENT_TEAM=3N2T3MD7F6 \
            OTHER_CODE_SIGN_FLAGS="--keychain build.keychain" \
            | tee "$CM_BUILD_DIR/xcodebuild.log" \
            | xcpretty --color || cat "$CM_BUILD_DIR/xcodebuild.log"

      - name: Export IPA
        script: |
          set -ex
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/UAWauto.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "$CM_BUILD_DIR/build/ios"

      - name: Print build log
        script: |
          echo "📄 Printing full build log:"
          cat "$CM_BUILD_DIR/xcodebuild.log"
